### ISSUE TITLE
REDO-DELAY BROKEN!! Players can cheat reward items!

### ISSUE THREAD

**Issue by ScuroK** [Blackvein/Quests#496] opened 2017-04-13 22:01 UTC
Version:
 Build #120 (05.02.2017 20:19:07)

Problem:
If a player completes a quest and relog (leave and join again) to the server he can do the quest again!
This enables them to chat rewards!

**Comment by MegaNarwhal** [comment] 2017-05-25 20:54
Any progress on this?

**Comment by Xoezer** [comment] 2017-06-05 12:26
^Bump

**Comment by FlyingPikachu** [comment] 2017-06-14 03:03
Duplicate of #329

**Closed by FlyingPikachu** 2017-06-14 03:03 UTC
