### ISSUE TITLE
Quest with time bug

### ISSUE THREAD

**Issue by TerZer** [Blackvein/Quests#376] opened 2016-07-10 14:37 UTC
When I finish quest, check time of quest and relog, it will let me start quest without cooldown.

**Comment by FlyingPikachu** [comment] 2016-07-10 18:44
Duplicate of #317

**Comment by FlyingPikachu** [comment] 2016-07-10 18:46
Re-opening because OP of #317 is unresponsive.

@TerZer Please upload your quests folder for testing. Thanks!

**Comment by TerZer** [comment] 2016-07-10 21:00
That's the bug: http://imgur.com/XXlFsQu
Folder: http://www105.zippyshare.com/v/400g5USh/file.html

**Comment by FlyingPikachu** [comment] 2016-07-13 02:59
@TerZer Could you please point out which quest you used for testing? I appreciate the video, but it is difficult to tell.

**Comment by TerZer** [comment] 2016-07-13 03:13
That quest called: Pagalba

**Comment by dadee971** [comment] 2016-07-29 14:21
Same issue:

I have a redo-delay prob.
Players just have to disconnect and reconnect and they can redo the quest without any delay.

CraftBukkit version git-Spigot-078e2f8-21e3b05 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

Quest 2.6.8.

**Comment by Legendaryx** [comment] 2016-12-08 08:18
I have the same issue. Is this being fixed or anything ?

**Comment by FlyingPikachu** [comment] 2017-06-20 01:01
Fixed in #535

**Closed by FlyingPikachu** 2017-06-20 01:01 UTC
Labels: bug
