### ISSUE TITLE
Deliver Items does not complete stage [Version 2.6.8 and 2.7.3]

### ISSUE THREAD

**Issue by scorpioservo** [Blackvein/Quests#430] opened 2016-10-10 17:59 UTC
On both of these versions of the plugin there is an issue with the delivery of items objective. When I deliver the item to the npc the says I delivered them but the stage does not complete. I have tried several workarounds to this issue but none fix it.

quests file below. This issue applies to the lost courier quest at the bottom. The 4th stage in the quest is a force completion event. It was my attempt to work around the bug

http://pastebin.com/1KqFCt5U

**Comment by ssamjh** [comment] 2016-10-12 11:50
I'd like to confirm this issue.

**Comment by RejcatkoCZ** [comment] 2016-10-15 11:58
I have the exactly same problem.

**Comment by zaxome** [comment] 2016-10-17 16:41
Same problem here.

**Comment by kamikazifroasty** [comment] 2016-11-08 09:12
same issue, same versions

**Comment by Volkenstein666** [comment] 2016-11-11 03:07
same problem - citizens2 - buildtools - quests all up to date

**Comment by FlyingPikachu** [comment] 2017-02-05 20:01
Duplicate of #416

**Closed by FlyingPikachu** 2017-02-05 20:01 UTC
