### ISSUE TITLE
Redo-delay broken

### ISSUE THREAD

**Issue by Xoezer** [Blackvein/Quests#502] opened 2017-04-30 18:34 UTC
Hi there,

Can you fix the redo-delay. When the server or the plugin restart then can a player repeat the same quest. 

Thanks for your corporation.

**Comment by FlyingPikachu** [comment] 2017-05-14 23:06
Likely duplicate of #496 

@Xoezer Please provide helpful information such as an example quest or errors in #496. Thanks!

**Closed by FlyingPikachu** 2017-05-14 23:06 UTC
