### ISSUE TITLE
Redo delay isn't working

### ISSUE THREAD

**Issue by Blamo27** [Blackvein/Quests#329] opened 2016-05-26 13:10 UTC
Redo delay isn't working, players can redo the quests instantly after finishing it. (Spigot 1.8.9)

**Comment by FlyingPikachu** [comment] 2016-06-03 05:57
@Blamo27 Post your Quests version and config settings, please.

**Comment by Blamo27** [comment] 2016-06-03 09:19
Quests version : 2.6.0-b99
Spigot version : 1.8.8

> language: en
allow-command-questing: true
allow-command-quests-with-npcs: false
show-requirements: true
allow-quitting: true
ignore-locked-quests: false
debug-mode: false
generate-files-on-join: true
kill-delay: 600
accept-timeout: 20
show-npc-effects: true
npc-effect: note
max-quests: 0
convert-data-on-startup: false

**Comment by FlyingPikachu** [comment] 2016-06-14 22:57
Could not replicate in testing. Please upload your Quests folder.

**Comment by Blamo27** [comment] 2016-06-19 01:05
I will have to send you that in a private message, how would you like me to send you that ? Also, to be more precise about my problem : it's only some players that are affected. Redo delays seem to be working perfectly fine globally, but sometimes, for no apparent reason, a specific player is able to redo instantly every quest without any delay, even though for other players, the redo delay is still working.

**Comment by FlyingPikachu** [comment] 2016-06-19 01:16
@Blamo27 This is a public repo, so sending the folder directly to me would ruin your chance of getting help from others should I become unavailable or cannot locate the issue. Additionally, there is no private messaging on Github. Quests does not save any sensitive information, but feel free to narrow down which players are affected and upload their data only.

**Comment by Blamo27** [comment] 2016-06-19 01:21
http://pastebin.com/abbTqPyv

**Comment by Blamo27** [comment] 2016-06-19 01:32
This is our quests.yml, and our events.yml. Do not hesitate to ask if you need anything else.
Quests.yml : http://pastebin.com/AsTUZ3XP
Events.yml : http://pastebin.com/YXWfQijy

**Comment by FlyingPikachu** [comment] 2016-06-19 01:51
In the player's data, i see there is a "null" value at the bottom of "completed-Quests". Try removing that line and try again.

Note: Appears to be duplicate of #67

**Comment by Blamo27** [comment] 2016-06-19 02:06
The timestamp is the same for everything, is it normal ?
- 1464002545832 (x13)

**Comment by Blamo27** [comment] 2016-06-19 02:06
=> I removed it

**Comment by Blamo27** [comment] 2016-06-19 02:11
So, we tried removing the "null" from the player data. We then proceeded to ask the player to take a redoable quest and finish it. He did, and after that he wasn't able to take the quest again (delay was working). However, he then disconnected, and reconnected, and the "null" appeared again, and the redo delay stopped working.

**Comment by Blamo27** [comment] 2016-06-22 21:04
@FlyingPikachu : Is this fixed with the last version ?

**Comment by FlyingPikachu** [comment] 2016-06-22 22:53
@Blamo27 Unlikely. Because I am unable to replicate this bug in my test environment, I am hoping others will be able to provide some insight.

**Comment by Blamo27** [comment] 2016-06-23 01:53
@FlyingPikachu ;(

**Comment by Blamo27** [comment] 2016-07-07 23:05
@FlyingPikachu The bug is still there, players have this bug when they disconnect from the server

**Comment by MClausz** [comment] 2016-07-13 06:11
I also have this issue, players can skip the redo delay by reconnecting to the server.

**Comment by Blamo27** [comment] 2016-07-13 12:31
@FlyingPikachu It's a big problem .. we need a fix for this issue ..

**Comment by Test1onplayfight** [comment] 2016-07-25 19:54
Hi, sorry for my bad english

The bug could happend when the serveur reloads, during a redoDelay of a players.

**Comment by Test1onplayfight** [comment] 2016-07-25 20:26
Sorry for 2 posts

I found how to make a "- null" in folder Data

I've a quests named 'bandit' (it's french)
In this quest you must kill a NPC. this quest works normaly

The "- null" appears when you get the quest when that NPC is dead.
So, you get a "- null" when the stage's quest does NOT existe.

If you can't understand what i wrote, plz tell me ^^

**Comment by Blamo27** [comment] 2016-07-26 04:17
@FlyingPikachu So there is a quest cooldown issue when the server is reloading, or restarting maybe ?
And when a player reconnect.

The bug is very annoying, we need an update to fix the Quest timestamp.
Thanks.

**Comment by Test1onplayfight** [comment] 2016-07-26 19:07
If you want, i can create a video to show you how to create the "- null"

(forget about the reload)

Plz correct my wrong english, it will help me ^^

**Comment by Blamo27** [comment] 2016-07-26 19:15
Oui je vais arranger ton Français ne t'inquiète pas mon petit, je vais tout lui expliquer.
Mais faudrait d’abord qu'il réponde. :p

**Comment by jk526** [comment] 2017-02-10 17:34
So is this still not fixed?
Having the same issue.

**Comment by jk526** [comment] 2017-02-18 11:42
I deleted all quest data and the jar file. Reinstalled and started making quests again. Not a week has passed and this bug has reappeared. :/ Is there still no fix?

**Comment by jk526** [comment] 2017-02-18 11:54
I attempted to replicate bug with the Kill a Dead NPC method mentioned above, but did not work. Haven't a clue what is causing it :/

**Comment by Test1onplayfight** [comment] 2017-03-21 13:58
There is a way...

I think, when you create a new quest, you can add some requested things

So you can create a fake redodelay with the command "scoreboard"
I think is : /scoreboard objectives add Time play stat.playOneMinute

You can choose any word in "Time"

The problem is that you must create a scoreboard for any quest.

**Comment by Test1onplayfight** [comment] 2017-03-21 16:04
(I don't know how to edit the previous msg sry ;/ )

Remember, with the score "playOneMinute", the countdown is in 'Ticks' and you must find a way to set the command (so the score) in the requested things ^^

**Closed** 2017-06-20 00:15 UTC
Labels: bug, help wanted
