### ISSUE TITLE
Many errors in you're plugin

### ISSUE THREAD

**Issue by Bluelanders** [Blackvein/Quests#360] opened 2016-06-26 22:41 UTC
This is a list of errors:

=) It is impossible to edit a quest in game
=) It is impossible to do quests with the order delivery item
=) It is impossible to do 2 talk to npc following

**Comment by FlyingPikachu** [comment] 2016-06-27 19:16
You need to provide more details. What version of Quests are you using? Do you have a version of Citizens that is compatible with your Spigot version? What is your Spigot version? Can you provide any error messages, either from in-game or the server log?

**Comment by Bluelanders** [comment] 2016-06-27 22:03
I'm using the last version 2.6.5 with a server in 1.10.
I buy citizens and i have the last version
Spigot 1.10
there are any errror message but the quests d'ont work i rightclick in a pnj and the quests don't check with message "no more quests available" and it is not normal because my quest is "talk to pnj".

**Comment by FlyingPikachu** [comment] 2016-06-27 22:13
Please post your startup log and quests.yml

**Comment by Bluelanders** [comment] 2016-06-28 11:48
[13:47:20 ERROR]: Error handling conversation prompt
java.lang.NullPointerException
        at me.blackvein.quests.QuestFactory$SavePrompt.acceptInput(QuestFactory.java:1031) ~[?:?]
        at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at org.bukkit.craftbukkit.v1_10_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1044) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at net.minecraft.server.v1_10_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1200) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at org.bukkit.craftbukkit.v1_10_R1.util.Waitable.run(Waitable.java:24) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
[13:47:23 ERROR]: Error handling conversation prompt
java.lang.NullPointerException
        at me.blackvein.quests.QuestFactory$SavePrompt.acceptInput(QuestFactory.java:1031) ~[?:?]
        at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at org.bukkit.craftbukkit.v1_10_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1044) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at net.minecraft.server.v1_10_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1200) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at org.bukkit.craftbukkit.v1_10_R1.util.Waitable.run(Waitable.java:24) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
[13:49:01 ERROR]: Error handling conversation prompt
java.lang.NullPointerException
        at me.blackvein.quests.QuestFactory$SavePrompt.acceptInput(QuestFactory.java:1031) ~[?:?]
        at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at org.bukkit.craftbukkit.v1_10_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1044) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at net.minecraft.server.v1_10_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1200) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at org.bukkit.craftbukkit.v1_10_R1.util.Waitable.run(Waitable.java:24) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot_1_10.jar:git-Spigot-c3e4052-1953f52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]

**Comment by FlyingPikachu** [comment] 2016-06-28 14:54
@Bluelanders Not what I asked for but that should help. Will look into it shortly.

**Comment by FlyingPikachu** [comment] 2016-06-28 15:45
@Bluelanders This error is caused by an issue loading your particular quests.yml file. Look over the file for syntax errors or post the file and someone might do it for you.

**Comment by sleite** [comment] 2016-08-31 01:01
No reply in 2 months.  I thinks it's safe to close this issue Pikachu.  :)

**Closed** 2016-09-01 01:05 UTC
