### ISSUE TITLE
Quests - Redodelay bug (reset after relog)

### ISSUE THREAD

**Issue by iSiiLeX** [Blackvein/Quests#400] opened 2016-08-12 18:00 UTC
The Redodelay resets if a User Logs out and Logs in. 
I got this bug on every Quest with redo delay.

**Comment by iSiiLeX** [comment] 2016-08-12 18:02
My delay is 10800 in the Config. (3h)

**Comment by FlyingPikachu** [comment] 2016-08-14 22:59
Duplicate of #376. Feel free to contribute there

**Closed by FlyingPikachu** 2016-08-14 22:59 UTC
