### ISSUE TITLE
Redo Delay Not working.

### ISSUE THREAD

**Issue by dadee971** [Blackvein/Quests#387] opened 2016-07-27 20:59 UTC
Hi,

I have a redo-delay prob.
Players just have to disconnect and reconnect and they can redo the quest without any delay.

CraftBukkit version git-Spigot-078e2f8-21e3b05 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

Quest 2.6.8.

**Comment by FlyingPikachu** [comment] 2016-07-28 06:59
Duplicate of #376

**Closed by FlyingPikachu** 2016-07-28 06:59 UTC
Labels: duplicate

**Comment by dadee971** [comment] 2016-07-28 10:50
Right but their are no solutions in #376

**Comment by FlyingPikachu** [comment] 2016-07-28 21:04
@dadee971 The is no reason to have a duplicate issue. Feel free to contribute in the ticket currently being worked on.
