### ISSUE TITLE
Noteparticle over head

### ISSUE THREAD

**Issue by Sprungente** [Blackvein/Quests#526] opened 2017-06-15 01:23 UTC
It isn't displayed in 1.12 Servers.  

Used: latest 1.12 Spigot Build
Latest Dev-Build from Quests

**Comment by FlyingPikachu** [comment] 2017-06-15 05:54
Duplicate of #523

Fixed in https://github.com/Blackvein/Quests/commit/7ef239ba4f541ac8335e80dfcda3bb4280a02748

**Closed by FlyingPikachu** 2017-06-15 05:54 UTC
