### ISSUE TITLE
Cannot Complete Quests Error 

### ISSUE THREAD

**Issue by shootcraft** [Blackvein/Quests#425] opened 2016-09-23 05:04 UTC
http://pastebin.com/SnJBHQ5F

**Comment by shootcraft** [comment] 2016-10-03 14:05
Hello can you fix trhis ?

**Comment by BloodSKreaper** [comment] 2016-10-25 19:14
#430

**Comment by FlyingPikachu** [comment] 2017-02-05 20:05
Duplicate of #416

**Closed by FlyingPikachu** 2017-02-05 20:05 UTC
