### ISSUE TITLE
permission problem

### ISSUE THREAD

**Issue by seema84** [Blackvein/Quests#344] opened 2016-06-15 00:17 UTC
the (negate) permission "- -quests.info" dont work - please fix

**Comment by FlyingPikachu** [comment] 2016-06-15 04:40
@seema84 Please provide more info such as Spigot version, Quests version, permissions plugin and error messages.

**Comment by seema84** [comment] 2016-06-16 00:06
CraftBukkit version git-Spigot-3ccadba-7f1a322 (MC: 1.10) (Implementing API version 1.10-R0.1-SNAPSHOT)
PermissionsEx v1.23.4
Quests Build #102
no error message

**Comment by FlyingPikachu** [comment] 2016-06-16 01:01
Tested with that setup and seemed to work fine. Post your permissions file?

**Comment by seema84** [comment] 2016-06-16 20:56
i have only set for this group
    - -quests.list
    - -quests.take
    - -quests.info
    - -quests.stats
list, take and stats works but not info
i cant hide info

**Comment by FlyingPikachu** [comment] 2016-06-17 00:21
@seema84 Unfortunately, I cannot replicate the issue. Unless there is an error message to work off of, or you are willing to provide the full permissions file for testing, there's nothing more I can do.

**Comment by seema84** [comment] 2016-06-17 16:54
my testserver with 3 plugins (vault,pex,quests)

pex:
groups:
  default:
    options:
      default: true
    permissions:
    - -quests.list
    - -quests.take
    - -quests.info
    - -quests.stats
schema-version: 1

and user in this default group can use /quests info
it is not difficult to reproduce

**Comment by FlyingPikachu** [comment] 2017-02-05 19:53
Closing due to inability to reproduce and lack of error message / _full_ permissions file per request.

**Closed by FlyingPikachu** 2017-02-05 19:53 UTC
