### ISSUE TITLE
Quests maxed?

### ISSUE THREAD

**Issue by Zeld0r** [Blackvein/Quests#471] opened 2017-01-31 07:54 UTC
On my server, it is my job to create quests, yet for some reason  I can no longer make anymore, after i create, save and reload, the quest is gone, and I only have 9 quests.

**Comment by FlyingPikachu** [comment] 2017-02-06 00:22
Duplicate of #437 

@Zeld0r Please contribute to the issue linked above instead. Thanks!

**Closed by FlyingPikachu** 2017-02-06 00:22 UTC
