### ISSUE TITLE
Break Block Event

### ISSUE THREAD

**Issue by pacificminer** [Blackvein/Quests#458] opened 2016-12-29 12:05 UTC
Break Block Event turns into Place Block Event.
Please fix, this has been an issue for so long on every version, including the latest 2.7.5

**Comment by johnsoncui02** [comment] 2017-01-15 11:19
i have the same issue too. including the cut blocks not working correctly. Here's a picture of me fished mining and it still didn't count as a block cutting.

![image](https://cloud.githubusercontent.com/assets/23487437/21962093/65df3d16-dad1-11e6-8d79-c4cc80ee448d.png)

**Comment by pacificminer** [comment] 2017-01-25 14:31
Oh well the developer does not care.

**Comment by johnsoncui02** [comment] 2017-01-26 04:49
i mean he doesn't respond to anything as of yet i've read through most of them. but im unsure if he reads them and attempts to fix the issues.

**Comment by pacificminer** [comment] 2017-01-26 12:09
Don't think he does. It seems like this plugin is dead.

**Comment by LeZalox** [comment] 2017-01-26 12:27
Is there any other good Quest plugin with similar features?

**Comment by FlyingPikachu** [comment] 2017-02-05 20:11
Duplicate of #458

**Closed by FlyingPikachu** 2017-02-05 20:11 UTC
